### ISSUE TITLE
grey colour not visible

### ISSUE THREAD

**Issue by smontanari** [gulpjs/fancy-log#18]
We all love our own personalised terminal colour settings. I've recently switched to using a version of a Solarized Dark theme that unfortunately makes the default ansi-gray color pretty much invisible. Is there any chance you would allow to make the timestamp colorisation configurable (say with a custom colour) or even just optional (so the console output falls back to whatever the standard is set for the current terminal)?
Thank you

**Comment by phated** [comment]
Output theming is planned for gulp-cli (see https://github.com/gulpjs/gulp-cli/issues/63) - I'm not sure how that will be propagated down into fancy-log or if it will be a layer on top.

**Comment by smontanari** [comment]
all right, thanks. I'll wait to see how that develops

**Comment by GongT** [comment]
![image](https://user-images.githubusercontent.com/2265048/50444276-82e44400-0942-11e9-884f-7a2b111e6766.png)
dark blue also not very visible. (which gulp not using)

**Comment by alessioalex** [comment]
any updates on this? unfortunately gray makes this logger unusable due to the date not being visible.

**Comment by kevin-smets** [comment]
This is effectively an issue with the theme, which is still open. See here: https://github.com/altercation/solarized/issues/220

A quick fix is to use Solarized Dark - patched: https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Solarized%20Dark%20-%20Patched.itermcolors

More info on the issue here: 
- https://github.com/mbadolato/iTerm2-Color-Schemes/issues/59
- https://github.com/mbadolato/iTerm2-Color-Schemes/pull/63

**Comment by phated** [comment]
Planning to "solve" this with #23 (and land in 2.0), which does 2 things:
1. Switches the color magenta—node's default color for Dates
2. Uses `utils.inspect` to allow color overrides following node's docs on custom formatting.
